name: SwissKnife
version: ${project.version}
main: com.egirlsnation.swissknife.SwissKnife
authors:
  - Lerbiq
  - Killmlana
api-version: 1.16
softdepend:
  - VotingPlugin
  - LuckPerms

commands:
  kill:
    description: Allows you to kill yourself or other players if you have perms
    usage: /kill
  playtime:
    description: Allows you to check the playtime of a player
    usage: /playtime
  shrug:
    description: /shrug
    usage: /shrug (args)
  ping:
    description: Pong
    usage: /ping (playername)
  shitlist:
    description: Allows you to shitlist someone if you have the permissions
    usage: /shitlist <add|remove> (playerName)
  refreshrank:
    description: Checks if you're eligible to rank up
    usage: /refreshrank
  monkey:
    description: Monkey
    usage: https://www.youtube.com/watch?v=5tQLFon8Yhk
  tpsalert:
    description: Test command for tps alert
    usage: /tpsalert
  toggleitemability:
    description: Allows you to toggle abilities of draconite items
    usage: /toggleitemability
  givepick:
    description: Gives pick
    usage: /givepick

permissions:
  swissknife.kill.others:
    description: Allows user to kill other players
    default: op
  swissknife.bypass.cooldown:
    description: Allows user to bypass cooldowns
    default: op
  swissknife.bypass.radius:
    description: Allows user to bypass radius checks
    default: op
  swissknife.bypass.combat:
    description: Allows user to bypass combat check
    default: op
  swissknife.bypass.fly:
    description: Allows user to bypass fly checks of this plugin
  swissknife.bypass.creative:
    description: Allows user to bypass all creative checks (includes swissknife.bypass.fly)
    default: op
  swissknife.chat.greentext:
    description: Allows user to prefix message with > to change color of the message to green
