name: SwissKnife
version: ${project.version}
main: com.egirlsnation.swissknife.SwissKnife
authors:
  - Lerbiq
  - Killmlana
api-version: 1.16
softdepend:
  - VotingPlugin
  - LuckPerms
  - Essentials
  - ProtocolLib

commands:
  kill:
    description: Allows you to kill yourself or other players if you have perms
    usage: /kill
  playtime:
    description: Allows you to check the playtime of a player
    usage: /playtime
  shrug:
    description: /shrug
    usage: /shrug (args)
  ping:
    description: Pong
    usage: /ping (playername)
  shitlist:
    description: Allows you to shitlist someone if you have the permissions
    usage: /shitlist <add|remove> (playerName)
  refreshrank:
    description: Checks if you're eligible to rank up
    usage: /refreshrank
  monkey:
    description: Monkey
    usage: /monkey
  tpsalerttest:
    description: Test command for tps alert
    usage: /tpsalerttest
  toggleitemability:
    description: Allows you to toggle abilities of draconite items
    usage: /toggleitemability
  swissknife:
    description: General swissknife command
    usage: /swissknife reload|info

permissions:
  swissknife.kill.others:
    description: Allows user to kill other players
    default: op
  swissknife.bypass.cooldown:
    description: Allows user to bypass cooldowns
    default: op
  swissknife.bypass.radius:
    description: Allows user to bypass radius checks
    default: op
  swissknife.bypass.combat:
    description: Allows user to bypass combat check
    default: op
  swissknife.bypass.fly:
    description: Allows user to bypass fly checks of this plugin
  swissknife.bypass.creative:
    description: Allows user to bypass all creative checks (includes swissknife.bypass.fly)
    default: op
  swissknife.bypass.illegals:
    description: Allows user to bypass all illegal checks
    default: op
  swissknife.bypass.roof:
    description: Allows user to bypass the nether roof checks
    default: op
  swissknife.chat.greentext:
    description: Allows user to prefix message with > to change color of the message to green
    default: op
  swissknife.chat.coords:
    description: Allows user to use the [coords] placeholder to display their position
    default: op
  swissknife.heads.nodrop:
    description: Prevents player from dropping head
    default: op
  swissknife.heads.chance.100:
    description: Player with this permission will have 100% chance of dropping their head
    default: not op
  swissknife.heads.chance.90:
    description: Player with this permission will have 90% chance of dropping their head
  swissknife.heads.chance.80:
    description: Player with this permission will have 80% chance of dropping their head
  swissknife.heads.chance.70:
    description: Player with this permission will have 70% chance of dropping their head
  swissknife.heads.chance.60:
    description: Player with this permission will have 60% chance of dropping their head
  swissknife.heads.chance.50:
    description: Player with this permission will have 50% chance of dropping their head
  swissknife.heads.chance.40:
    description: Player with this permission will have 40% chance of dropping their head
  swissknife.heads.chance.30:
    description: Player with this permission will have 30% chance of dropping their head
  swissknife.heads.chance.20:
    description: Player with this permission will have 20% chance of dropping their head
  swissknife.heads.chance.10:
    description: Player with this permission will have 10% chance of dropping their head
  swissknife.heads.chance.05:
    description: Player with this permission will have 5% chance of dropping their head
